# PyTorch基本操作

In [23]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

### 1.pytorchのインポートとバージョン確認

In [24]:
import torch
torch.__version__

'1.0.0'

### 2.テンソルの作成 <br>
多次元配列(テンソル)の作成。引数で(2, 2)を指定

In [25]:
x = torch.Tensor(2, 2)
x

tensor([[ 0.0000e+00,  2.5244e-29],
        [-1.3498e-05, -4.6577e-10]])

### 3.テンソルの作成<br>
リストからテンソルの作成

In [26]:
list = [[1,2,3], [4,5,6]]
list

[[1, 2, 3], [4, 5, 6]]

In [27]:
x2 = torch.Tensor(list)
x2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### 4.テンソルのサイズ確認

In [28]:
x2.size()

torch.Size([2, 3])

### 5.乱数の生成<br>
一様分布の乱数生成

In [29]:
torch.rand(2,2)

tensor([[0.5629, 0.9145],
        [0.7289, 0.2954]])

正規分布の乱数生成

In [30]:
torch.randn(2,2)

tensor([[1.8942, 0.5896],
        [0.2059, 1.7803]])

### 6.特別な行列の生成
単位行列の作成

In [31]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

空のテンソルの作成

In [32]:
torch.empty(4, 1)

tensor([[ 0.0000e+00],
        [ 2.5244e-29],
        [-1.3711e-05],
        [-2.8601e-42]])

等間隔の数列

In [33]:
torch.linspace(0, 100, 11)

tensor([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### 7.基本演算

In [40]:
x = torch.Tensor([[2, 2], [1, 1]])
y = torch.Tensor([[3, 2],[1, 2]])
x
y

tensor([[2., 2.],
        [1., 1.]])

tensor([[3., 2.],
        [1., 2.]])

足し算

In [41]:
x + y

tensor([[5., 4.],
        [2., 3.]])

アダマール積

In [42]:
x * y
torch.mul(x, y)

tensor([[6., 4.],
        [1., 2.]])

tensor([[6., 4.],
        [1., 2.]])

積

In [43]:
torch.mm(x, y)

tensor([[8., 8.],
        [4., 4.]])

和

In [49]:
torch.sum(x)

tensor(6.)

標準偏差

In [50]:
torch.std(x)

tensor(0.5774)

算術平均

In [51]:
torch.mean(x)

tensor(1.5000)